/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import db.Koneksi;
import helper.DateHelper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Mobil;
import model.Pelanggan;
import model.Transaksi;

/**
 *
 * @author whois
 */
public class TambahTransaksiFrame extends javax.swing.JFrame {

    String nopolSelected = "";
    String ktpSelected = "";

    /**
     * Creates new form TambahTransaksiFrame
     */
    public TambahTransaksiFrame() {
        initComponents();
        setLocationRelativeTo(null);
        loadMobilCombo();
        loadPelangganCombo();
        cbMobil.addActionListener(new MobilListener());
        cbPelanggan.addActionListener(new PelangganListener());
    }

    public ArrayList<Mobil> getMobilList() {
        ArrayList<Mobil> mobilList = new ArrayList<>();
        Koneksi koneksi = new Koneksi();
        Connection connection = koneksi.getConnection();

        String query = "SELECT * FROM mobil WHERE status = 1 ORDER BY merk";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            while (rs.next()) {
                Mobil mobil = new Mobil(
                        rs.getString("nopol"),
                        rs.getString("merk"),
                        rs.getString("warna"),
                        rs.getInt("tahun"),
                        rs.getInt("harga_sewa"),
                        rs.getBoolean("status"));
                mobilList.add(mobil);
            }
        } catch (SQLException | NullPointerException ex) {
            System.out.println("Gagal melakukan query : " + ex.getMessage());
        }
        return mobilList;
    }

    private void loadMobilCombo() {
        cbMobil.removeAllItems();
        List<Mobil> mobilList = getMobilList();
        for (Mobil mbl : mobilList) {
            cbMobil.addItem(mbl);
        }
    }

    private class MobilListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Mobil mobil = (Mobil) cbMobil.getSelectedItem();
            nopolSelected = mobil.getNopol();
            etHarga.setText(Integer.toString(mobil.getHargaSewa()));
        }

    }

    public ArrayList<Pelanggan> getPelangganList() {
        ArrayList<Pelanggan> pelangganList = new ArrayList<>();
        Koneksi koneksi = new Koneksi();
        Connection connection = koneksi.getConnection();

        String query = "SELECT * FROM pelanggan "
                + "ORDER BY nama";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            while (rs.next()) {
                Pelanggan pelanggan = new Pelanggan(
                        rs.getString("ktp"),
                        rs.getString("nama"),
                        rs.getString("alamat"),
                        rs.getString("hp"));
                pelangganList.add(pelanggan);
            }
        } catch (SQLException | NullPointerException ex) {
            System.out.println("Gagal melakukan query : " + ex.getMessage());
        }
        return pelangganList;
    }

    private void loadPelangganCombo() {
        cbPelanggan.removeAllItems();
        List<Pelanggan> pelanngganList = getPelangganList();
        for (Pelanggan plg : pelanngganList) {
            cbPelanggan.addItem(plg);
        }
    }

    private class PelangganListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Pelanggan pelanggan = (Pelanggan) cbPelanggan.getSelectedItem();
            ktpSelected = pelanggan.getKtp();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpTanggalMulai = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btTambahTransaksi = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        etHarga = new javax.swing.JTextField();
        tvBiaya = new javax.swing.JLabel();
        dpTanggalAkhir = new org.jdesktop.swingx.JXDatePicker();
        cbPelanggan = new javax.swing.JComboBox<>();
        cbMobil = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dpTanggalMulai.setFormats("yyyy-MM-dd");
        dpTanggalMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpTanggalMulaiActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah Transaksi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setText("Pelanggan");

        jLabel3.setText("Mobil");

        jLabel4.setText("Harga per Hari");

        jLabel5.setText("Tanggal Mulai");

        jLabel6.setText("Tanggal Akhir");

        jLabel7.setText("Biaya");

        btTambahTransaksi.setBackground(new java.awt.Color(0, 204, 102));
        btTambahTransaksi.setText("Tambahkan Transaksi");
        btTambahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahTransaksiActionPerformed(evt);
            }
        });

        btBatal.setText("Batal");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });

        tvBiaya.setText("0");

        dpTanggalAkhir.setFormats("yyyy-MM-dd");
        dpTanggalAkhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpTanggalAkhirActionPerformed(evt);
            }
        });

        cbPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPelangganActionPerformed(evt);
            }
        });

        jLabel8.setText("Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btTambahTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBatal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etHarga)
                            .addComponent(cbPelanggan, 0, 245, Short.MAX_VALUE)
                            .addComponent(cbMobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tvBiaya))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dpTanggalMulai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dpTanggalAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(dpTanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(dpTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(etHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvBiaya)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btTambahTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dpTanggalMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpTanggalMulaiActionPerformed

    }//GEN-LAST:event_dpTanggalMulaiActionPerformed

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btBatalActionPerformed

    private void cbPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPelangganActionPerformed

    }//GEN-LAST:event_cbPelangganActionPerformed

    private void dpTanggalAkhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpTanggalAkhirActionPerformed
        String tanggalMulai = DateHelper.dateToString(dpTanggalMulai.getDate());
        String tanggalAkhir = DateHelper.dateToString(dpTanggalAkhir.getDate());

        Transaksi transaksi = new Transaksi();
        transaksi.setHargaSewa(Integer.parseInt(etHarga.getText()));

        transaksi.setWaktuMulai(tanggalMulai);
        transaksi.setWaktuSelesai(tanggalAkhir);

        try {
            int totalHarga = transaksi.getTotalHarga();
            tvBiaya.setText(Integer.toString(totalHarga));
        } catch (ParseException ex) {
            Logger.getLogger(TambahTransaksiFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dpTanggalAkhirActionPerformed

    private void btTambahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahTransaksiActionPerformed

        if ("".equals(ktpSelected) || "".equals(nopolSelected)) {
            JOptionPane.showMessageDialog(
                    null, "Harap memilih pelanggan dan mobil terlebih dahulu!"
            );
            return;
        }

        insertToTransaksi();
        updateMobilStatus();
        dispose();
    }//GEN-LAST:event_btTambahTransaksiActionPerformed

    private void insertToTransaksi() {

        try {
            Koneksi koneksi = new Koneksi();
            Connection conn = koneksi.getConnection();

            PreparedStatement ps;
            String executeQuery = "insert into sewa "
                    + "(ktp,nopol,harga_sewa,waktu_mulai,waktu_selesai) "
                    + "values(?,?,?,?,?)";
            ps = conn.prepareStatement(executeQuery);
            ps.setString(1, ktpSelected);
            ps.setString(2, nopolSelected);
            ps.setInt(3, Integer.parseInt(etHarga.getText()));
            ps.setString(4, DateHelper.dateToString(dpTanggalMulai.getDate()));
            ps.setString(5, DateHelper.dateToString(dpTanggalAkhir.getDate()));

            ps.executeUpdate();
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }

    private void updateMobilStatus() {
        try {
            Koneksi koneksi = new Koneksi();
            Connection conn = koneksi.getConnection();

            PreparedStatement ps;
            String executeQuery = "update mobil set "
                    + "status=? "
                    + "WHERE nopol=?";
            ps = conn.prepareStatement(executeQuery);
            ps.setBoolean(1, false);
            ps.setString(2, nopolSelected);

            ps.executeUpdate();
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahTransaksiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btTambahTransaksi;
    private javax.swing.JComboBox<Mobil> cbMobil;
    private javax.swing.JComboBox<Pelanggan> cbPelanggan;
    private org.jdesktop.swingx.JXDatePicker dpTanggalAkhir;
    private org.jdesktop.swingx.JXDatePicker dpTanggalMulai;
    private javax.swing.JTextField etHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tvBiaya;
    // End of variables declaration//GEN-END:variables
}
